# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
