# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='appmanager',
            field=models.CharField(default='approver', max_length=254),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_start',
            field=models.DateField(),
        ),
    ]
