# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='hours',
            field=models.FloatField(),
        ),
    ]
