# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20191120_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='appmanager',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
