# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20191120_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Unactioned', 'Unactioned'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Unactioned', max_length=254),
        ),
    ]
