# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='estab',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rota',
        ),
    ]
