# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-13 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('nurseing', 'nursing'), ('hca', 'hca'), ('admin', 'admin')], max_length=254)),
                ('location', models.CharField(choices=[('bingham', 'bingham'), ('cropwell', 'cropwell'), ('cotgrave', 'cotgrave')], default='bingham', max_length=254)),
                ('job_title', models.CharField(default='jobtitle', max_length=254)),
                ('starting_salary', models.IntegerField(default=1000)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dbs_number', models.CharField(default=0, max_length=254)),
                ('start_date', models.DateField(auto_now=True)),
                ('new_start', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
