# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_overtime_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='appmanager',
            field=models.CharField(default='none', max_length=254),
            preserve_default=False,
        ),
    ]
