# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_overtime_appmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='appmanager',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
