# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-29 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0006_overtime_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='appmanagerun',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
