# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-30 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_overtime_appmanagerun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='hours',
        ),
    ]
