# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-30 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0008_remove_overtime_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=3),
            preserve_default=False,
        ),
    ]
