# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0009_overtime_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='Date',
            field=models.DateField(help_text='DD/MM/YY'),
        ),
    ]
