# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0010_auto_20191209_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='status',
            field=models.CharField(choices=[('Unactioned', 'Unactioned'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='unactioned', max_length=254),
        ),
    ]
