# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0011_overtime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='status',
            field=models.CharField(choices=[('Unactioned', 'Unactioned'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Unactioned', max_length=254),
        ),
    ]
