# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-19 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0012_auto_20191219_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='approved',
        ),
    ]
