# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0013_remove_overtime_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='ot_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='overtime',
            name='ot_type',
            field=models.CharField(choices=[('normal', 'normal'), ('extended', 'extended')], default='normal', max_length=254),
        ),
    ]
