# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('nurseing', 'nursing'), ('hca', 'hca'), ('admin', 'admin')], max_length=254)),
                ('location', models.CharField(choices=[('bingham', 'bingham'), ('cropwell', 'cropwell'), ('cotgrave', 'cotgrave')], default='bingham', max_length=254)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('day', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=254)),
                ('hours', models.DecimalField(decimal_places=0, max_digits=2)),
                ('info', models.TextField()),
            ],
        ),
    ]
