# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0002_auto_20191114_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='username',
            field=models.CharField(default='unallocated', max_length=254),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
