# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estab', '0003_auto_20200624_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifts',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='shifts',
            name='shift_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shifts',
            name='shift_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shifts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
