# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estab', '0003_auto_20191115_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='user',
            field=models.ForeignKey(default='unallocated', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
