# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0004_auto_20200624_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='shiftname',
        ),
    ]
