# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0005_auto_20191116_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='username',
        ),
    ]
