# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0006_remove_establishment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='username',
            field=models.CharField(default='unallocated', max_length=254),
        ),
    ]
