# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0008_auto_20191116_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
