# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0008_auto_20200627_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='day',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='shift_end',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='shift_start',
        ),
    ]
