# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0009_auto_20200628_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shifts',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='shifts',
            name='shift_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shifts',
            name='shift_start',
            field=models.TimeField(null=True),
        ),
    ]
