# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0009_auto_20191116_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=254),
        ),
    ]
