# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0010_auto_20191118_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='width',
            field=models.CharField(default='20', max_length=254),
        ),
    ]
