# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0011_establishment_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='hours',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
