# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0013_auto_20191124_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
