# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0014_auto_20191206_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
