# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0015_auto_20200109_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='username',
        ),
    ]
