# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab', '0016_remove_establishment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
    ]
