# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-12 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(default='approver', max_length=254, null=True)),
                ('absence_start', models.DateField()),
                ('absence_end', models.DateField()),
                ('gp_consult', models.BooleanField(default=False)),
                ('further_support', models.TextField()),
                ('days', models.CharField(max_length=254)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
