# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='absence',
            name='reason',
            field=models.CharField(default='reason', max_length=254),
            preserve_default=False,
        ),
    ]
