# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-13 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_auto_20191213_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='days',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='further_support',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
