# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_auto_20200619_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_end',
            field=models.DateField(null=True),
        ),
    ]
