# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_auto_20191213_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
