# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_auto_20191213_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='days',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='further_support',
            field=models.TextField(blank=True, null=True),
        ),
    ]
