# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0006_auto_20191213_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='reason',
        ),
        migrations.AddField(
            model_name='absence',
            name='reason',
            field=models.ManyToManyField(to='absence.Reason'),
        ),
    ]
