# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0007_auto_20191216_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.ManyToManyField(blank=True, null=True, to='absence.Reason'),
        ),
    ]
