# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-13 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201112_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pot',
        ),
        migrations.AddField(
            model_name='profile',
            name='Driving_lic',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='Passport_Number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_of_kin_name',
            field=models.CharField(default='My Name', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_address1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_address2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='town_or_city',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
