# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_pot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leave',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pot',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
