# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-13 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201113_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='media/profiles'),
            preserve_default=False,
        ),
    ]
