# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=254)),
                ('month_num', models.IntegerField()),
            ],
        ),
    ]
