# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20191203_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='months',
            name='month_num',
            field=models.IntegerField(default=0),
        ),
    ]
