# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-08 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='worked',
            field=models.CharField(choices=[('Worked Extra', 'Time Off')], max_length=254, null=True),
        ),
    ]
