# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0002_pot_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='worked',
            field=models.CharField(choices=[('Worked Extra', 'Worked Extra'), ('Time Off', 'Time Off')], max_length=254, null=True),
        ),
    ]
