# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-08 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0003_auto_20191208_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='worked',
            field=models.CharField(choices=[('pluspot', 'pluspot'), ('minuspot', 'minuspot')], max_length=254, null=True),
        ),
    ]
